services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8001:8001"
      - "8000:8000"  # Expose Prometheus metrics
    volumes:
      - ./models:/app/models
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000 || exit 1"]
      interval: 5s
      retries: 5

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      server:
        condition: service_healthy

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "5001:5000"
    restart: always
