name: Python Tests

on:
  push:
    branches:
      - feat/implement-testing  # Trigger the workflow on push to the said branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The operating system for the runner

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 4: Lint the code with flake8
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint server/ client/ ui/ --exit-zero

    # Step 5: Run tests
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/test_main.py